dateModified: 1565993933
email:
  fromEmail: leong.shi.yun@gmail.com
  fromName: 'Craft Lyrics'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  a1a22de2-f817-4935-ab69-e9c381cb95ca:
    name: Globals
  ad0a1114-70de-435f-b6de-88777d4235e4:
    name: Common
fields:
  1bb183bd-4ebe-4a41-8380-0c2098bee689:
    name: Theme
    handle: theme
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\Dropdown
    settings:
      optgroups: true
      options:
        -
          label: Black
          value: black
          default: '1'
        -
          label: White
          value: white
          default: ''
        -
          label: League
          value: league
          default: ''
        -
          label: Sky
          value: sky
          default: ''
        -
          label: Beige
          value: beige
          default: ''
        -
          label: Simple
          value: simple
          default: ''
        -
          label: Serif
          value: serif
          default: ''
        -
          label: Blood
          value: blood
          default: ''
        -
          label: Night
          value: night
          default: ''
        -
          label: Moon
          value: moon
          default: ''
        -
          label: Solarized
          value: solarized
          default: ''
    contentColumnType: string
    fieldGroup: a1a22de2-f817-4935-ab69-e9c381cb95ca
  25a66925-81db-4de5-8c35-739d31c717a3:
    name: Tagline
    handle: tagline
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: a1a22de2-f817-4935-ab69-e9c381cb95ca
  56942ba7-16e0-46b4-a9df-9513469b96e4:
    name: Favicon
    handle: favicon
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: ''
      defaultUploadLocationSource: 'volume:a72bd4a1-090a-49b9-9cba-d1b9452e0c80'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:a72bd4a1-090a-49b9-9cba-d1b9452e0c80'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources:
        - 'volume:a72bd4a1-090a-49b9-9cba-d1b9452e0c80'
      source: null
      targetSiteId: null
      viewMode: large
      limit: '1'
      selectionLabel: 'Select favicon'
      localizeRelations: false
      validateRelatedElements: ''
    contentColumnType: string
    fieldGroup: a1a22de2-f817-4935-ab69-e9c381cb95ca
  5ca3318e-7a9c-4396-a74b-61f96b927c1c:
    name: 'Selection Background'
    handle: selectionBackground
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: ''
      defaultUploadLocationSource: 'volume:a72bd4a1-090a-49b9-9cba-d1b9452e0c80'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:a72bd4a1-090a-49b9-9cba-d1b9452e0c80'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: large
      limit: '1'
      selectionLabel: 'Select a background image'
      localizeRelations: false
      validateRelatedElements: ''
    contentColumnType: string
    fieldGroup: a1a22de2-f817-4935-ab69-e9c381cb95ca
  72adcfcd-4ae7-4422-a9f1-775e49d1cdb6:
    name: 'Landing Background'
    handle: landingBackground
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: ''
      defaultUploadLocationSource: 'volume:a72bd4a1-090a-49b9-9cba-d1b9452e0c80'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:a72bd4a1-090a-49b9-9cba-d1b9452e0c80'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: large
      limit: '1'
      selectionLabel: 'Select a background image'
      localizeRelations: false
      validateRelatedElements: ''
    contentColumnType: string
    fieldGroup: a1a22de2-f817-4935-ab69-e9c381cb95ca
  d25313f6-d21e-4e23-b1ba-28ef0f3bdf15:
    name: Heading
    handle: heading
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: a1a22de2-f817-4935-ab69-e9c381cb95ca
  efb5cc63-9470-4fcd-b009-3820a909fc89:
    name: 'Sub Heading'
    handle: subHeading
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: a1a22de2-f817-4935-ab69-e9c381cb95ca
globalSets:
  8a742345-041f-46e8-8ce6-c2803e5a2d25:
    name: Globals
    handle: globals
    fieldLayouts:
      b8c43733-8e22-489d-9c28-e5480f9b25e9:
        tabs:
          -
            name: Settings
            sortOrder: 1
            fields:
              1bb183bd-4ebe-4a41-8380-0c2098bee689:
                required: true
                sortOrder: 4
              25a66925-81db-4de5-8c35-739d31c717a3:
                required: false
                sortOrder: 3
              d25313f6-d21e-4e23-b1ba-28ef0f3bdf15:
                required: false
                sortOrder: 1
              efb5cc63-9470-4fcd-b009-3820a909fc89:
                required: false
                sortOrder: 2
          -
            name: Media
            sortOrder: 2
            fields:
              56942ba7-16e0-46b4-a9df-9513469b96e4:
                required: false
                sortOrder: 1
              5ca3318e-7a9c-4396-a74b-61f96b927c1c:
                required: false
                sortOrder: 3
              72adcfcd-4ae7-4422-a9f1-775e49d1cdb6:
                required: false
                sortOrder: 2
siteGroups:
  91c81b4d-7dd3-4dd1-82fe-ece0ca8518f5:
    name: 'Craft Lyrics'
sites:
  edf2f59c-3f24-402a-9203-e4296026583c:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en
    name: 'Craft Lyrics'
    primary: true
    siteGroup: 91c81b4d-7dd3-4dd1-82fe-ece0ca8518f5
    sortOrder: 1
system:
  edition: solo
  name: 'Craft Lyrics'
  live: true
  schemaVersion: 3.2.16
  timeZone: America/Los_Angeles
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  a72bd4a1-090a-49b9-9cba-d1b9452e0c80:
    name: Images
    handle: images
    type: craft\volumes\Local
    hasUrls: true
    url: '@web/uploads'
    settings:
      path: '@webroot/uploads'
    sortOrder: 1
